### ISSUE TITLE
Mod sometimes copies NBT incorrectly

### ISSUE THREAD

**Issue by Moonyol** [zabi94/NBTTooltip#43]
**Describe the bug**
If you attempt to copy an item with the character ' or " in its NBT, for example egg{display:{Name:'{"text":"a\'a"}'}} and attempt to copy it, it will alter the NBT by changing it to egg{"display":{"Name":"{\"text\":\"a\'a\"}"}} which changes the quotations around the Name tag however if you look at the NBT while it is still inside your inventory it will display the correct type of quotations

**To Reproduce**
1. Do /give @p egg{display:{Name:'{"text":"a\"a"}'}}
2. Copy the NBT
3. Attempt to give yourself the item with /give
4. It doesn't work

**Expected behavior**
It should've copied the NBT from the item without changing it which would make the give command work properly

**Screenshots**
![image](https://github.com/zabi94/NBTTooltip/assets/92951072/b999d671-788a-4560-8856-ebad3ef82234)
![image](https://github.com/zabi94/NBTTooltip/assets/92951072/18c10123-574a-4ce3-9b7b-2e1bbd341c73)

**Pastebin links**
Don't paste the whole lists here, use **pastebin**
 - ![image](https://github.com/zabi94/NBTTooltip/assets/92951072/4eb7dbaa-18ca-42f5-a2ad-7cfa32e793b1)
 - ![image](https://github.com/zabi94/NBTTooltip/assets/92951072/4d7332cd-b371-4c62-bcad-4fb470daf286)

**Environment (please complete the following information):**
 - Mod Version: 1.7.1
 - MC Version: 1.19.4
 - Fabric Version: 0.14.19
 - Fabric API version: 0.80.0
 - System: Windows 10
 - Installation type: Singleplayer and Multiplayer

**Additional context**
Add any other context about the problem here, like other mods that you think might be involved in the problem.

**Comment by zabi94** [comment]
When you use the give command and specify an nbt tag, the tag is not saved as a string exactly as you type it.
The tag is saved as a tree of values. In your case it is saving the 'Name' property as a string, which is a child of the 'display' property.
The itemstack itself has no data on what kind of quotes you used, they get lost in the abstraction.
I'm using double quotes when rebuilding the string by default, since this is not meant to be an advanced instrument but only something I use to debug my other mods. 

If it doesn't break your logic, you can invert the type of all quotation marks in your command to work around the issue
